name: Bug
description: Something broke
title: "[bug] "
labels: ["bug","triage"]
body:
  - type: textarea
    id: steps
    attributes: { label: Steps to reproduce }
    validations: { required: true }
  - type: textarea
    id: expected
    attributes: { label: Expected vs actual }
    validations: { required: true }
  - type: textarea
    id: logs
    attributes: { label: Logs }
