name: Feature
description: Request / idea
title: "[feature] "
labels: ["feature","triage"]
body:
  - type: textarea
    id: proposal
    attributes: { label: Proposal }
    validations: { required: true }
